### ISSUE TITLE
The help for the dataset with labeled regions

### ISSUE THREAD

**Issue by tqwang743** [keyalone/EnDecon#3]
Hi,

It is a fantastic method for analyzing spatial transcriptomics!

I have found datasets related to PDAC-A and PDAC-B based on the information you provided, but none of these datasets have labeled regions like the following picture in your paper. I would appreciate it if you could share the datasets with labeled regions or let me know which file is the label in.
<img width="357" alt="image" src="https://github.com/keyalone/EnDecon/assets/108932740/8dc5226a-6d52-4c48-a8d9-d8678228ee4d">
![image](https://github.com/keyalone/EnDecon/assets/108932740/74db5ca8-cd9d-484d-ae72-f09d1af7db0e)
Thank you very much!

**Comment by TJJjiajuan** [comment]
Hi tqwang,
Thank you for your interest in this work. The spot labels indicating region information can be obtained from the original paper titled "Integrating microarray-based spatial transcriptomics and single-cell RNA-seq reveals tissue architecture in pancreatic ductal adenocarcinomas," as illustrated in Figure 2a,
![image](https://github.com/user-attachments/assets/25318476-c5c8-48ac-b91b-9cafbd9b2aae).
Please note that the authors do not provide the spot label information for these regions on the GEO website. 
You can annotate the spot area information based on Figure 2a above.
